spring:
  application:
    name: auth-server
  data:
    mongodb:
      authentication-database: admin
      database: travel-app
      host: localhost
      password: admin
      port: 27018
      username: admin
      auto-index-creation: true
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: efbaf1924aa2b3c0df98
            clientSecret: ${GITHUB_APPLICATION_SECRET}
  mail:
    protocol: smtp

    # Gmail config
#    host: smtp.gmail.com
#    port: 465
#    username: ${GMAIL_EMAIL}
#    password: ${GMAIL_PASSWORD}

    # Yandex config
    host: smtp.yandex.ru
    port: 587
    username: ${YANDEX_EMAIL}
    password: ${YANDEX_PASSWORD}

    properties:
      "mail.transport.protocol": smtp
      "mail.smtp.auth": true
      "mail.smtp.starttls.enable": true
#      "mail.smtp.ssl.enable": true


app-version: "1.0"

authorization:
  # temporary solution
  secret: temporarySecret

  # right solution
  #secret: ${AUTH_SECRET}


server:
  port: 0

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka

mongock:
  migration-scan-package: com.vas.travelapp.migration
