spring:
  application:
    name: auth-server
  data:
    mongodb:
      authentication-database: admin
      database: travel-app
      host: ${mongo}
      password: ${mongopass}
      port: 27017
      username: ${mongouser}
      auto-index-creation: true
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: ${GITHUB_APPLICATION_ID}
            clientSecret: ${GITHUB_APPLICATION_SECRET}
  mail:
    protocol: smtp

    # Gmail config
    host: smtp.gmail.com
    port: 465
    username: ${GMAIL_EMAIL}
    password: ${GMAIL_PASSWORD}

    # Yandex config
#    host: smtp.yandex.ru
#    port: 587
#    username: ${YANDEX_EMAIL}
#    password: ${YANDEX_PASSWORD}

    properties:
      "mail.transport.protocol": smtp
      "mail.smtp.auth": true
      "mail.smtp.starttls.enable": true
#      "mail.smtp.ssl.enable": true


app-version: "1.0"

authorization:
  secret: ${AUTH_SECRET}


refresh-token:
  expiration-in-minutes: 10080 # 60m * 24h * 7d - one week

registration-token:
  expiration-in-minutes: 1440 # 60m * 24h - one day

password-reset-token:
  expiration-in-minutes: 1440 # 60m * 24h - one day


server:
  port: 0

eureka:
  client:
    service-url:
      defaultZone: http://${eureka}:8761/eureka

mongock:
  migration-scan-package: com.vas.travelapp.migration
