app-version: "1.0"
authorization:
  secret: ${AUTH_SECRET}
spring:
  data:
    mongodb:
      authentication-database: admin
      database: travel-app
      host: localhost
      password: admin
      port: 27017
      username: admin
