app-version: "1.0"
authorization:
  secret: "TGNqaCtOUzVNZFdSerSXhZelEyTFRJelMVJrRmAbobaME5wUlZaRWN0ZUhsehMUT09"
spring:
  datasource:
    name: PostgresConnection
    driver-class-name: org.postgresql.Driver
    username: galex
    url: jdbc:postgresql://localhost:5433/
  jpa:
    open-in-view: false
    show-sql: false
    database: postgresql
    properties:
      hibernate:
        show_sql: false
        use_sql_comments: false
        format_sql: false
        ddl-auto: create-drop
    generate-ddl: true

poi-poller:
  enabled: true
  cron: "0 */5 * * * *"
  placesApiUrl: "https://maps.googleapis.com/maps/api/place"
  placesKey: "AIzaSyDjdzrAAagAOpb7ekzXaDniBUn8JgYynnA"