app-version: "1.0"
authorization:
  secret: "TGNqaCtOUzVNZFdSerSXhZelEyTFRJelMVJrRmAbobaME5wUlZaRWN0ZUhsehMUT09"
spring:
  datasource:
    name: PostgresConnection
    driver-class-name: org.postgresql.Driver
    password: toor
    username: postgres
    url: jdbc:postgresql://localhost:5433/
  jpa:
    open-in-view: false
    show-sql: false
    database: postgresql
    properties:
      hibernate:
        show_sql: false
        use_sql_comments: false
        format_sql: false
        ddl-auto: create-drop
    generate-ddl: true