app-version: "1.0"
authorization:
  # temporary solution
  secret: temporarySecret

  # right solution
  #secret: ${AUTH_SECRET}

spring:
  application:
    name: core
  data:
    mongodb:
      authentication-database: admin
      database: travel-app
      host: localhost
      password: admin
      port: 27017
      username: admin

server:
  port: 0

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
