app-version: "1.0"

authorization:
  secret: temporarySecret

spring:
  application:
    name: core
  datasource:
    name: PostgresConnection
    driver-class-name: org.postgresql.Driver
    password: toor
    username: postgres
    url: jdbc:postgresql://localhost:5433/
  jpa:
    open-in-view: false
    show-sql: false
    database: postgresql
    properties:
      hibernate:
        show_sql: false
        use_sql_comments: false
        format_sql: false
        ddl-auto: create-drop
    generate-ddl: true

server:
  port: 0

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka